    #include p18f45k20.inc
    CONFIG FOSC=INTIO67
    CONFIG WDTEN=OFF
    
INTCOUNT EQU 04
SWPT EQU 05
TIMER2 EQU 0A
    ORG 0
    GOTO MAIN
    
    ORG 8 ;ISR here
    MOVFF INTCOUNT,0
    CPFSGT SWPT
    BRA CLROUT
    BSF PORTD,0
    BRA AHEAD
CLROUT
    BCF PORTD,0
AHEAD MOVLW D'99' 
    CPFSLT INTCOUNT
    BRA RSTINT
    INCF INTCOUNT 
AHEAD2
    BCF T0CON,TMR0ON
    MOVLW D'231' ;INTERRUPTS EVERY 100
    MOVWF TMR0L ;?s
    BSF T0CON,TMR0ON ;RESTART TMR0
    BCF INTCON,TMR0IF ;CLEAR INTERRUPT FLAG RETFIE 1 ;RESTORE W AND STATUS
    RETFIE 1
RSTINT
    CLRF INTCOUNT
    BRA AHEAD2

    ORG 100
MAIN BCF TRISD,0 
     BSF TRISC,0 
     BSF TRISC,1
    CLRF INTCOUNT 
    MOVLW D'50' 
    MOVWF SWPT ;cycle MOVLW 
    IORLW b'01001000'
    MOVWF T0CON 
    MOVF INTCON,0 
    IORLW b'10100000' 
    MOVWF INTCON 
    BSF T0CON,7
LOOP1 BTFSC PORTC,0
    BRA UP
CHKDWN
    BTFSS PORTC,1
    BRA LOOP1 
    MOVLW d'1' 
    CPFSGT SWPT 
    BRA LOOP1 
    DECF SWPT 
    CALL DELAY 
    BRA LOOP1
UP MOVLW d'98' 
   CPFSLT SWPT 
   BRA CHKDWN
   INCF SWPT 
   CALL DELAY 
   BRA CHKDWN
DELAY
   MOVLW D'255'
   MOVWF 0x04
   MOVLW D'255'
   MOVWF 0x05
   DECF 0x05
   BNZ $-02h
   DECF 0x04
   BNZ $-0x0A
   RETURN
   
   END

    